### ISSUE TITLE
Automatic retry on networking issues (ETIMEDOUT, ECONNRESET etc.)

### ISSUE THREAD

**Issue by zubairov** [elasticio/rest-api-component-v2#10]
Automatically retry HTTP call in case request failure due network errors (ETIMEDOUT, ECONNRESET etc.), 5 times. If call failed after this usual [logic for handling HTTP 400-500 error codes](https://github.com/elasticio/rest-api-component-v2#exception-handling) should be applied

**Comment by jhorbulyk** [comment]
Related: https://github.com/elasticio/elasticio/issues/4874
