### ISSUE TITLE
Investigate: support content-type ndjson

### ISSUE THREAD

**Issue by andrewreshitko** [elasticio/rest-api-component-v2#35]
# Other Feature Request

## Request from SQUIZ:
We have a request to support ndjson content-type header using the REST component. The use case is for bulk import data into the Datastore service via the importing API.  Here is the API spec: https://docs.squiz.net/datastore/latest/using/importing.html#adding-an-import-block

It requires Content-Type: application/x-ndjson

To reference something similar here.   Previously, there was one ticket related to the ability to overwrite the content-type header for the REST component : https://support.elastic.io/support/tickets/7116(ticket discussion is in the comments). But the requirement was too broad and we ended up working around the problem. 

Can you please provide feedback on what's the viable option to support this integration?  
for example: 
option 1: adding support to content-type: application/x-ndjson
option 2: adding feature to override header content-type
option 3: if neither 1 or 2 is viable,  a new component?

### Updates (bi-weekly call 19.01.23):
The content type in the component is not free-form.
Content type as a placeholder text in the header section but if you change to POST request and the user goes through it, then presenting a dropdown with pre-defined content types. Users are confused about why they can't use x-nd JSON.

**Comment by andrewreshitko** [comment]
Related old ticket [#7116 in screenshots below:]( https://support.elastic.io/support/tickets/7116)
Related [GitHub task](https://github.com/elasticio/rest-api-component/issues/59)

![image.png](https://images.zenhubusercontent.com/62e29e867f5f6f5963aac5de/48d0992e-cdaf-4db5-8edf-52476ec2d376)
![image.png](https://images.zenhubusercontent.com/62e29e867f5f6f5963aac5de/d1e0576b-56a2-4c3e-b956-8cb597a42786)
![image.png](https://images.zenhubusercontent.com/62e29e867f5f6f5963aac5de/b0b7df18-d9e1-45f2-9c3c-ab3b6d884db6)
![image.png](https://images.zenhubusercontent.com/62e29e867f5f6f5963aac5de/013ca2c3-48eb-4a99-8928-cd0a65894a1a)
![image.png](https://images.zenhubusercontent.com/62e29e867f5f6f5963aac5de/08e62049-c511-4636-b040-6ddbe133bfda)

**Comment by A3a3e1** [comment]
If the platform team extends the UI view class `RESTAPIView` with the `application/x-ndjson` type this should do the trick. No extra work is required from us

**Comment by A3a3e1** [comment]
Closing the task so far. There are workarounds we could do but they require creating a new component. The simplest solution is adding this content type tho the existing viewclass by the platform team
