### ISSUE TITLE
Revitalise the component

### ISSUE THREAD

**Issue by andrewreshitko** [elasticio/rest-api-component-v2#43]
## Description

Based on this [case](https://elasticio.slack.com/archives/C6G1E4WB1/p1726572884358819
) we need to revitalise the component:
- Libraries
- Attachment mechanism

## Definition of Done

[What you expected to be implemented]

**Comment by KERERCVASD** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/rest-api-component-v2/releases/tag/2.1.0
