### ISSUE TITLE
oauth2 creds cannot be saved after edit done (cannot be edited)

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/rest-api-component-v2#7]
**Description:** oauth2 creds with a faceless client could be created but cannot be saved in case of an edit attempt

**STR**
1. Create oauth2 creds -> choose existing Auth Client -> authenticate -> verify and save creds.
2. try to edit created creds: authenticate -> verify -> get error on save in devtools

**AR:**
1. can not edit oauth2 credentials 
2. Error in devtools:
```
{"errors":[{"detail":"\"data.attributes.credentials.scope\" is not allowed to be empty","status":400,"code":400,"title":"\"data.attributes.credentials.scope\" is not allowed to be empty","meta":{}}]}
```
**ER:** User is able to edit oauth2 creds

**Comment by if0s** [comment]
Can't be reproduced
